# Generated by Django 5.1.1 on 2024-10-01 18:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0004_user_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=60, unique=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(max_length=40, unique=True, validators=[django.core.validators.RegexValidator(message='Логин может содержать только латиницу, цифры и тире.', regex='^[a-zA-Z0-9-]+$')], verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Имя может содержать только кириллицу, пробелы и тире.', regex='^[А-Яа-яЁё\\s-]+$')], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='patronymic',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator(message='Отчество может содержать только кириллицу, пробелы и тире.', regex='^[А-Яа-яЁё\\s-]*$')], verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Фамилия может содержать только кириллицу, пробелы и тире.', regex='^[А-Яа-яЁё\\s-]+$')], verbose_name='Фамилия'),
        ),
    ]
