# Generated by Django 5.1.1 on 2024-10-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_first_name_remove_order_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancellation_reason',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Причина отмены'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='Новый', max_length=50, verbose_name='Статус заказа'),
        ),
    ]
