# Generated by Django 5.1.1 on 2024-10-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_cancellation_reason_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Новый', 'Новый'), ('Отменен', 'Отменен'), ('Подтвержден', 'Подтвержден')], default='Новый', max_length=50, verbose_name='Статус заказа'),
        ),
    ]
